# Generated by Django 4.2 on 2023-04-11 02:07

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('emplacement', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('frais_livraison', models.DecimalField(decimal_places=2, max_digits=6)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.customuser')),
                ('adresse_livraison', models.CharField(max_length=255)),
            ],
            bases=('main.customuser',),
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('adresse', models.CharField(default='Unknown', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('restaurant', 'Restaurant'), ('supermarché', 'Supermarche'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantite', models.PositiveIntegerField()),
                ('professionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.professionnel')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('est_livre', models.BooleanField(default=False)),
                ('boxes', models.ManyToManyField(to='main.box')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produit')),
                ('professionnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.professionnel')),
                ('service_livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.servicedelivraison')),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.customuser')),
                ('professionnels', models.ManyToManyField(related_name='administrateurs', to='main.professionnel')),
            ],
            bases=('main.customuser',),
        ),
    ]
